paste/urls.py
from django.conf.urls import patterns, url

from paste import views

urlpatterns = [
    url(r'^list/$', views.PasteCodeListView.as_view(), name='list'),
    url(r'^(?P<pk>[-\w]+)/$', views.PasteCodeDetailView.as_view(), name='detail'),
    url(r'^detail__code/(?P<pk>[-\w]+)/$', views.PasteCodeDetailCodeView.as_view(), name='detail__code'),
]

paste_code/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import logout, login

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

from userprofile.forms import AuthenticationForm
from paste.views import PasteCodeCreateView

urlpatterns = [
    url(r'^$', PasteCodeCreateView.as_view(), name='add'),
    url(r'^(?P<pk>[-\w]+)/$', PasteCodeCreateView.as_view(), name='edit'),
    url(r'^paste/', include('paste.urls', app_name='paste', namespace='paste')),
    url(r'^profile/', include('userprofile.urls', app_name='profile', namespace='profile')),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += [
    url(r'^login/$', login, {'template_name': 'pages/login.html',
                             'authentication_form': AuthenticationForm}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/login'}, name='logout'),
]

urlpatterns += [
    url('^register/', CreateView.as_view(
        template_name='register.html',
        form_class=UserCreationForm,
        success_url='/'
    ), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/menus/globlal_menu.html
{% load staticfiles i18n %}

<nav class="navbar-top navbar-fixed-top">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="navbar-wrapper">
                    <div class="navbar navbar-inverse navbar-static-top" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                    data-target="#nav-top-b">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span><span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="/">
                                <img src="{% static 'img/zinaBrand.png' %}" alt="Powered by ZINA Dev team">
                            </a>
                        </div>
                        <div class="navbar-collapse collapse" id="nav-top-b">
                        {% if request.user.is_authenticated %}
                            <ul class="nav navbar-nav navbar-right">
                                <li class="profile dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <span class="glyphicon glyphicon-user"></span>
                                        {{ user.profile.get_prefix|default:user.username|capfirst }}
                                        <b class="caret"></b>
                                    </a>
                                    
                                        <ul class="dropdown-menu profile-menu">
                                        <li>
                                            <div class="navbar-content">
                                                <div class="row">
                                                    <div class="col-md-5">
                                                        <div id="img-avatar">
                                                            {% if user.profile.picture %}
                                                                <img src="{{ user.profile.picture.url }}"
                                                                     alt="{{ user.profile.get_prefix }}"
                                                                     class="img-circle img-responsive"/>
                                                            {% else %}
                                                                <img src="http://lorempixel.com/104/104/abstract/"
                                                                     alt="{{ user.profile.get_prefix }}"
                                                                     class="img-circle img-responsive"/>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                    <div class="col-md-7">
                                                        <span>{{ user.profile.get_prefix|default:user.username|capfirst }}</span>

                                                        <p class="text-muted small">{{ user.email }}</p>

                                                        <div class="divider"></div>
                                                            <a href=""
                                                               class="btn btn-primary btn-sm btn-block {% if CURRENT_VIEW_NAME == 'about' or CURRENT_APP_NAME == 'profile' %}active{% endif %}">
                                                                <span class="glyphicon glyphicon-user"></span>
                                                                {% trans 'My profile' %}
                                                            </a>

                                                            <div class="divider"></div>
                                                            <a href="">
                                                                <i class="fa fa-info-circle"></i>
                                                                {% trans 'About' %}
                                                            </a>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="navbar-footer">
                                                <div class="navbar-footer-content">
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                        </div>
                                                        <div class="col-md-6">
                                                            <a href="{% url 'logout' %}"
                                                               class="btn btn-default btn-sm pull-right">
                                                                <i class="fa fa-sign-out"></i>
                                                                {% trans 'Logout' %}
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

templates/menus/menu.html
{% load staticfiles i18n %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <!-- Second navbar for profile settings -->
            {% load staticfiles i18n %}
            <nav class="navbar navbar-inverse">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#navbar-collapse-4">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-collapse-4">
                    <ul id="main_menu" class="nav navbar-nav">
                        <li><a href="/">{% trans 'Home' %}</a></li>
                        <li><a href="{% url 'paste:list' %}">{% trans 'List' %}</a></li>
                    </ul>

                </div>
                <!-- /.navbar-collapse -->
            </nav>

            <!-- /.navbar -->
        </div>
        <!-- /.container-fluid -->
    </div>
</div>

templates/menus/search.html
{% load staticfiles i18n %}
<div class="container-fluid logo-app">
    <div class="row">
        <div class="col-lg-3">
            <a href="/"><img class="claro-delivery-logo" src="{% static 'img/logo-claro-delivery.png' %}"
                                            alt="ZINA Claro invoice delivery"></a>
        </div>
        <!--<div class="col-lg-6 search-main">
            <form action="" class="" method="get">
                <div class="input-group">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">Select filter <span
                                class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="#">Invoice</a></li>
                            <li><a href="#">Electronic invoice</a></li>
                            <li><a href="#">Protocol number </a></li>
                        </ul>
                    </div>
                    
                    <input type="text" class="form-control" aria-label="Text input with dropdown button">
								<span class="input-group-btn btn-search">
									<button class="btn btn-primary" type="button"><span
                                            class="glyphicon glyphicon-search"></span></button>
								</span>
                </div>
            </form>
        </div>-->
    </div>
</div>