paste/urls.py
from django.conf.urls import patterns, url

from paste import views

urlpatterns = [
    url(r'^list/$', views.PasteCodeListView.as_view(), name='list'),
    url(r'^(?P<pk>[-\w]+)/$', views.PasteCodeDetailView.as_view(), name='detail'),
    url(r'^detail__code/(?P<pk>[-\w]+)/$', views.PasteCodeDetailCodeView.as_view(), name='detail__code'),
]

paste_code/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import logout, login

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

from userprofile.forms import AuthenticationForm
from paste.views import PasteCodeCreateView

urlpatterns = [
    url(r'^$', PasteCodeCreateView.as_view(), name='add'),
    url(r'^(?P<pk>[-\w]+)/$', PasteCodeCreateView.as_view(), name='edit'),
    url(r'^paste/', include('paste.urls', app_name='paste', namespace='paste')),
    url(r'^profile/', include('userprofile.urls', app_name='profile', namespace='profile')),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += [
    url(r'^login/$', login, {'template_name': 'pages/login.html',
                             'authentication_form': AuthenticationForm}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/login'}, name='logout'),
]

urlpatterns += [
    url('^register/', CreateView.as_view(
        template_name='register.html',
        form_class=UserCreationForm,
        success_url='/'
    ), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

paste/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

# Create your models here.
from paste.choices import HIGHLIGHT_LANGUAGES


class LanguageCode(models.Model):
    language = models.CharField(_('language'), unique=True, max_length=144)
    language_slug = models.CharField(_('Highlight language'), max_length=144, default='', choices=HIGHLIGHT_LANGUAGES)

    def __unicode__(self):
        return u'{}'.format(self.language)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.language_slug = slugify(self.language)
        super(LanguageCode, self).save(force_insert=force_insert, force_update=force_update, using=using,
                                       update_fields=update_fields)

    class Meta:
        ordering = ('language',)


class PasteCode(models.Model):
    code = models.TextField(_('code'))
    language = models.ForeignKey('paste.LanguageCode', verbose_name=_('language'))
    user = models.ForeignKey('auth.User', verbose_name=_('User'))
    comment = models.CharField(_('comment'), max_length=255, null=True, blank=True)
    created = models.DateTimeField(_('created'), auto_now_add=True)

    def __unicode__(self):
        return u'{0} - {1}'.format(self.language, self.user, self.comment)

paste/views.py
from django.http.response import HttpResponse
from django.contrib.auth.models import User
from django.views.generic import CreateView, DetailView, ListView
from django.core.urlresolvers import reverse

from paste.choices import HIGHLIGHT_LANGUAGES
from paste.models import PasteCode, LanguageCode


# Create your views here.


class PasteCodeCreateView(CreateView):
    model = PasteCode
    fields = ('language', 'comment', 'code')

    def get_success_url(self):
        return reverse('paste:detail', args=(self.object.id,))

    def get_initial(self):
        initial = super(PasteCodeCreateView, self).get_initial()
        if not self.kwargs.get('pk'):
            initial['language'] = LanguageCode.objects.filter(language_slug=HIGHLIGHT_LANGUAGES.Python).last()
        return initial

    def get_form_kwargs(self):
        kwargs = super(PasteCodeCreateView, self).get_form_kwargs()
        if self.kwargs.get('pk') and PasteCode.objects.filter(id=self.kwargs.get('pk')).exists():
            kwargs['instance'] = PasteCode.objects.get(id=self.kwargs.get('pk'))
        return kwargs

    def form_valid(self, form):
        paste_code = form.save(commit=False)
        paste_code.id = None
        if self.request.user.is_authenticated():
            user = self.request.user
        else:
            user = User.objects.first()
        paste_code.user = user
        paste_code.save()
        return super(PasteCodeCreateView, self).form_valid(form)


class PasteCodeDetailView(DetailView):
    model = PasteCode


class PasteCodeDetailCodeView(DetailView):
    model = PasteCode

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return HttpResponse(self.object.code)


class PasteCodeListView(ListView):
    model = PasteCode

paste/templates/paste/pastecode_detail.html
{% extends "base.html" %}
{% load i18n static %}
{% block extracss %}
    <link rel="stylesheet" id="theme" href="{% static 'css/prism.css' %}">
    <link rel="stylesheet" id="theme" href="{% static 'css/prism-line-numbers.css' %}">
{% endblock %}
{% block main_section %}
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-12">
            <h4>[{{ pastecode.language }}] [{{ pastecode.created }}]{% if pastecode.comment %} [{{ pastecode.comment }}]{% endif %}</h4>
                <div class="form-inline pull-right">
                    <div>
                        <button class="btn" data-clipboard-text="{{ pastecode.code }}">
                            <i class="glyphicon glyphicon-copy"></i> {% trans 'Copy to clipboard' %}
                        </button>
                        <a class="btn btn-primary" href="{% url 'edit' pastecode.id %}">
                            <i class="glyphicon glyphicon-pencil"></i> {% trans 'Edit' %}
                        </a>
                        <label for="themes">{% trans 'Themes' %}: </label>
                        <select class="form-control" name="theme" id="themes">
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <pre class="line-numbers language-{{ pastecode.language.language_slug }}" data-src="{% url 'paste:detail__code'  pastecode.id %}">
                    <code class="language-{{ pastecode.language.language_slug }}"></code>
                </pre>
            </div>
        </div>
    </div>
{% endblock %}
{% block extrajs %}
    <script src="{% static 'js/clipboard.min.js' %}" data-manual></script>
    <script src="{% static 'js/prism.js' %}" data-manual></script>
    <script src="{% static 'js/prism-line-numbers.js' %}" data-manual></script>
    <script>
        $(function () {
            var clipboard = new Clipboard('.btn');
            var default_theme = "{% static 'css/prism-okaidia.css' %}";
            var themes = [
                ['{% static 'css/prism-okaidia.css' %}', 'Okaidia'],
                ['{% static 'css/prism.css' %}', 'Default'],
                ['{% static 'css/prism-coy.css' %}', 'Coy'],
                ['{% static 'css/prism-dark.css' %}', 'Dark'],
                ['{% static 'css/prism-funky.css' %}', 'Funky'],
                ['{% static 'css/prism-twilight.css' %}', 'Twilight'],
                ['{% static 'css/prism-solarizedlight.css' %}', 'Solarized light'],
            ];
            themes.forEach(function (value) {
                var $option = $('<option value="' + value[0] + '">' + value[1] + '</option>')
                $('#themes').append($option);
            });
            $('#theme').attr('href', default_theme);
            $('#themes').on('change', function (evt) {
                $('#theme').attr('href', $(this).val());
            });
        })
    </script>
{% endblock %}

paste/templates/paste/pastecode_form.html
{% extends 'base.html' %}
{% load static i18n tags_html %}
{% block main_section %}
    <div class="row">
        <form action="" method="post">
            {% if form.non_field_errors %}
                <div id="login-alert" class="alert alert-danger">
                    {% for error in form.non_field_errors %}
                        {{ error|safe }}
                    {% endfor %}
                </div>
            {% endif %}
            {% csrf_token %}
            <div class="form-group col-md-3">
                {{ form.language.label }}
                {{ form.language|addclass:'form-control' }}
                {% for error in form.language.errors %}
                    <span class="glyphicon glyphicon-info-sign text-danger"></span>{{ error }}
                {% endfor %}
            </div>
            <div class="form-group col-md-9">
                {{ form.comment.label }}
                {{ form.comment|addclass:'form-control' }}
                {% for error in  form.comment.errors %}
                    <span class="glyphicon glyphicon-info-sign text-danger"></span>{{ error }}
                {% endfor %}
            </div>
            <div class="form-group col-md-12">
                {{ form.code.label }}
                {{ form.code|addclass:'form-control'|set_rows:'20' }}
                {% for error in  form.code.errors %}
                    <span class="glyphicon glyphicon-info-sign text-danger"></span>{{ error }}
                {% endfor %}
            </div>
            <div class="form-group col-md-12">
                <button type="submit" class="btn btn-primary pull-right">{% trans 'Save' %}</button>
            </div>
        </form>
    </div>
{% endblock %}

paste/templates/paste/pastecode_list.html
{% extends "base.html" %}
{% load staticfiles i18n   static %}
{% block main_section %}
    <div class="row">
        <div class="col-md-10">
            <div class="title-wrapper">
                <h1>{% trans 'Paste code list' %}</h1>
            </div>
        </div>
        {% if is_search %}
            <div class="col-md-2 text-right">
                <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#displayFilter1"
                        aria-expanded="false" aria-controls="displayFilter1">
                    <span class="glyphicon glyphicon-filter"></span> {% trans 'Display filters' %}
                </button>
            </div>
        {% endif %}
    </div>
    {% if search_form %}
        <div class="row">
            <div class="col-md-12 collapse" id="displayFilter1">
                <div class="panel with-nav-tabs panel-default">
                    <div class="panel-heading">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab1default" data-toggle="tab">{% trans 'Filter' %}</a></li>
                        </ul>
                    </div>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="tab1default">
                                {% if is_search %}
                                    {% include 'forms/search_form.html' %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="row">

        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-datatable" id="table_nf_list_importers">
                    <thead>
                    <tr>
                        <th class="text-center">{% trans 'ID' %}</th>
                        <th class="text-center">{% trans 'USER' %}</th>
                        <th class="text-center">{% trans 'LANGUAGE' %}</th>
                        <th class="text-center">{% trans 'CREATED' %}</th>
                        <th class="text-center">{% trans 'COMMENT' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for pastecode in pastecode_list %}
                        <tr class="text-center">
                            <td>
                                <a href="{% url 'paste:detail' pastecode.id %}">{{ pastecode.id }}</a>
                            </td>
                            <td>{{ pastecode.user }}</td>
                            <td>{{ pastecode.language }}</td>
                            <td>{{ pastecode.created }}</td>
                            <td>{{ pastecode.comment }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}